"""Human- and agent-readable projections of a project's canonical graph."""

from __future__ import annotations

import json
from pathlib import Path
import re

from sqlalchemy.orm import Session

from . import models, reference_service


def _safe_segment(value: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", value.strip()).strip(". ")
    return cleaned or "unnamed"


def _atomic_write(path: Path, content: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def _item_line(db: Session, item_id: int) -> str:
    item = db.query(models.Item).filter(models.Item.id == item_id).first()
    if not item:
        return f"- `gaia:item:{item_id}` — missing"
    return f"- `gaia:item:{item.id}` — `{item.type}` — `{item.absolute_path}`"


def write_project_context(db: Session, project_id: int) -> dict[str, Path]:
    """Regenerate Markdown without ever treating it as graph input."""
    project = db.query(models.ProjectItem).filter(models.ProjectItem.id == project_id).first()
    if not project:
        raise ValueError("Project not found")
    root = Path(project.absolute_path)
    root.mkdir(parents=True, exist_ok=True)
    (root / "notes").mkdir(exist_ok=True)
    stages_root = root / "stages"
    stages_root.mkdir(exist_ok=True)

    references = reference_service.list_references(db, project_id)
    master = reference_service.resolve_master(db, project_id)
    source_references = [reference for reference in references if reference.relation_kind == "source"]

    sources_lines = [f"# Sources — {project.title or root.name}", ""]
    if source_references:
        for reference in source_references:
            sources_lines.append(_item_line(db, reference.to_item_id))
    else:
        sources_lines.append("_No sources linked yet._")
    sources_path = root / "SOURCES.md"
    _atomic_write(sources_path, "\n".join(sources_lines) + "\n")

    context_lines = [
        f"# {project.title or root.name}",
        "",
        "This file is generated by GAIA. The SQLite reference graph is canonical.",
        "",
        "## Project",
        "",
        f"- `gaia:item:{project.id}`",
        f"- Managed folder: `{root}`",
        f"- Master status: `{master['status']}`",
    ]
    if master.get("resolved_item_id"):
        context_lines.append(f"- Effective master: `gaia:item:{master['resolved_item_id']}`")
    context_lines.extend(["", "## References", ""])
    if references:
        for reference in references:
            details = [reference.relation_kind]
            if reference.stage_name:
                details.append(f"stage={reference.stage_name}")
            if reference.revision_label:
                details.append(f"revision={reference.revision_label}")
            if reference.is_master:
                details.append("master")
            context_lines.append(
                f"- `gaia:reference:{reference.id}` — `gaia:item:{reference.from_item_id}` → "
                f"`gaia:item:{reference.to_item_id}` ({', '.join(details)})"
            )
    else:
        context_lines.append("_No relationships created yet._")
    context_lines.extend(["", "## Integrity", ""])
    resolved_id = master.get("resolved_item_id")
    if resolved_id:
        resolved = db.query(models.Item).filter(models.Item.id == resolved_id).first()
        status = reference_service.integrity_status(resolved) if resolved else "missing"
        context_lines.append(f"- Effective master: `{status}`")
    else:
        context_lines.append("- No master selected.")
    context_path = root / "PROJECT_CONTEXT.md"
    _atomic_write(context_path, "\n".join(context_lines) + "\n")

    for reference in references:
        if not reference.stage_name or not reference.revision_label:
            continue
        stage_dir = stages_root / _safe_segment(reference.stage_name)
        stage_dir.mkdir(parents=True, exist_ok=True)
        version_path = stage_dir / f"VERSION_{_safe_segment(reference.revision_label)}.md"
        version = {
            "reference_id": reference.id,
            "from_item_id": reference.from_item_id,
            "to_item_id": reference.to_item_id,
            "relation_kind": reference.relation_kind,
            "stage_name": reference.stage_name,
            "revision_label": reference.revision_label,
            "is_master": bool(reference.is_master),
            "attributes": reference.attributes,
        }
        _atomic_write(
            version_path,
            f"# {reference.stage_name} — {reference.revision_label}\n\n"
            "```json\n"
            f"{json.dumps(version, indent=2, sort_keys=True)}\n"
            "```\n",
        )
    return {"context": context_path, "sources": sources_path}
